### ISSUE TITLE
-mode=server ERROR

### ISSUE THREAD

**Issue by JessyGothik** [teamdfir/sift-saltstack#103]
I can't run the next syntax: sudo cast install teamdfir/sift --mode=server, because appear a error:
dfir@scilabs:~/Downloads$ sudo cast install teamdfir/sift --mode=server

FATA[0000] please provide a distro alias to install     

What's the problem?

**Comment by JessyGothik** [comment]
Sorry. I changed my syntax to: **sudo cast install --mode=server teamdfir/sift**, and solved.

Thanks

**Comment by ekristen** [comment]
Yeah arguments are positional unfortunately. Glad you got it worked out.
