### ISSUE TITLE
repo.saltproject.io error during sift-salstack install

### ISSUE THREAD

**Issue by agafonoo** [teamdfir/sift-saltstack#116]
Expected behavior: 

`cast install --log-level debug --mode desktop teamdfir/sift-saltstack`

should install SIFT.

Actual behavior:

![Screenshot from 2024-11-04 15-48-42](https://github.com/user-attachments/assets/bbeae2ab-1eab-45dd-931a-49de5d56fb4c)

Binary url at repo.saltproject.io/salt/singlebin/3005.1-1/salt-3005.1-1-linux-amd64.tar.gz is no longer valid.

**Comment by ekristen** [comment]
Download the latest version of [cast](https://github.com/ekristen/cast)

**Comment by ekristen** [comment]
Please know there are known issues with installing SIFT at the moment beyond needing the latest version of `cast`. It is actively being worked on.
